# Dockerfile

# Use a recent, stable PHP version with Apache. PHP 8.1 is a good choice.
# Your script uses JSON_THROW_ON_ERROR (PHP 7.3+) and random_int (PHP 7.0+).
FROM php:8.1-apache

# Install system dependencies that might be needed by PHP extensions
RUN apt-get update && apt-get install -y \
    libzip-dev \
    zip \
    && rm -rf /var/lib/apt/lists/*

# Install PHP extensions required by the script:
# - curl: For making API calls to LimeSurvey
# - json: For json_encode/decode (usually enabled by default, but good to ensure)
# - mbstring: For multi-byte string functions (used by htmlspecialchars for UTF-8)
# - opcache: Highly recommended for performance in production
# - zip: If you were to handle zip files (not directly used here but common)
RUN docker-php-ext-install curl json mbstring opcache zip

# Enable Apache's mod_rewrite (good practice, though not strictly needed by this single script)
RUN a2enmod rewrite

# Set the working directory inside the container
WORKDIR /var/www/html

# Copy the main PHP script into the container
# The config.php file will be generated by entrypoint.sh using environment variables
COPY leaderboard.php /var/www/html/leaderboard.php

# Copy the entrypoint script and make it executable
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Expose port 80 for Apache
EXPOSE 80

# Set the entrypoint script to run when the container starts
# This script will generate config.php and then start Apache
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Default command if entrypoint.sh doesn't exec another one (it will exec apache2-foreground)
CMD ["apache2-foreground"]
