#!/bin/sh
set -e  # Exit immediately if any command fails

# Where we want the generated config to live
CONFIG_FILE="/var/www/html/config.php"

###############################################################################
# 1. Generate config.php from Render environment variables
###############################################################################
cat <<'PHP' > "${CONFIG_FILE}"
<?php
// ---------------------------------------------------------------------------
//  This file is auto‑generated by entrypoint.sh at container startup.
//  DO NOT edit it inside the container. Values come from environment vars.
// ---------------------------------------------------------------------------

// Required LimeSurvey API details
define('LIMESURVEY_API_URL',  getenv('LIMESURVEY_API_URL')  ?: '');
define('LIMESURVEY_USERNAME', getenv('LIMESURVEY_USERNAME') ?: '');
define('LIMESURVEY_PASSWORD', getenv('LIMESURVEY_PASSWORD') ?: '');
define('LIMESURVEY_SURVEY_ID', (int)(getenv('LIMESURVEY_SURVEY_ID') ?: 0));

// Question codes (override via env‑vars if they differ)
define('COLUMN_NICKNAME', getenv('COLUMN_NICKNAME') ?: 'nickname');
define('COLUMN_SCORE',   getenv('COLUMN_SCORE')   ?: 'totalScore');

// Optional UI strings
if (getenv('LEADERBOARD_TITLE'))      define('LEADERBOARD_TITLE',      getenv('LEADERBOARD_TITLE'));
if (getenv('SEARCH_PLACEHOLDER'))     define('SEARCH_PLACEHOLDER',     getenv('SEARCH_PLACEHOLDER'));
if (getenv('NO_RESULTS_MESSAGE'))     define('NO_RESULTS_MESSAGE',     getenv('NO_RESULTS_MESSAGE'));
if (getenv('POINTS_SUFFIX'))          define('POINTS_SUFFIX',          getenv('POINTS_SUFFIX'));
if (getenv('NO_SCORES_MESSAGE'))      define('NO_SCORES_MESSAGE',      getenv('NO_SCORES_MESSAGE'));
?>
PHP

###############################################################################
# 2. Minimal diagnostics (shell‑safe echo/printf)
###############################################################################
echo "-------------------------------------------------------------------"
echo "SUCCESS: ${CONFIG_FILE} generated."
echo "🔍  Verifying required env‑vars:"
[ -n "$LIMESURVEY_API_URL"  ] && echo "  LIMESURVEY_API_URL   : SET" || echo "  LIMESURVEY_API_URL   : NOT SET"
[ -n "$LIMESURVEY_USERNAME" ] && echo "  LIMESURVEY_USERNAME  : SET" || echo "  LIMESURVEY_USERNAME  : NOT SET"
if [ -n "$LIMESURVEY_SURVEY_ID" ] && [ "$LIMESURVEY_SURVEY_ID" -gt 0 ]; then
  echo "  LIMESURVEY_SURVEY_ID : $LIMESURVEY_SURVEY_ID"
else
  echo "  LIMESURVEY_SURVEY_ID : NOT SET or INVALID"
fi
echo "  COLUMN_NICKNAME      : ${COLUMN_NICKNAME:-nickname}"
echo "  COLUMN_SCORE         : ${COLUMN_SCORE:-totalScore}"
echo "-------------------------------------------------------------------"

###############################################################################
# 3. Hand off to the main container command (Apache)
###############################################################################
exec "$@"
