#!/bin/sh
set -e # Exit immediately if a command exits with a non-zero status.

# Path to the config file to be generated
CONFIG_FILE="/var/www/html/config.php"

# Create config.php from environment variables
# Ensure these environment variables are set in your Render service
cat <<EOF > "${CONFIG_FILE}"
<?php
// This file is auto-generated by entrypoint.sh at container startup.
// Do not edit this file directly in the container.
// Configuration is sourced from environment variables.

// Required Limesurvey API connection details
define('LIMESURVEY_API_URL', getenv('LIMESURVEY_API_URL') ?: '');
define('LIMESURVEY_USERNAME', getenv('LIMESURVEY_USERNAME') ?: '');
define('LIMESURVEY_PASSWORD', getenv('LIMESURVEY_PASSWORD') ?: ''); // Password can be empty string if intended
define('LIMESURVEY_SURVEY_ID', (int)(getenv('LIMESURVEY_SURVEY_ID') ?: 0));

// Required Limesurvey Question Codes for leaderboard data
// It's crucial these match your Limesurvey question codes exactly.
// Defaults are set here to your specific values, but ENV VARS on Render will override.
define('COLUMN_NICKNAME', getenv('COLUMN_NICKNAME') ?: 'nickname'); // Default to 'nickname'
define('COLUMN_SCORE', getenv('COLUMN_SCORE') ?: 'totalScore');   // Default to 'totalScore'

// Optional: Customizable text strings for the leaderboard
// Define them if the environment variable is set, otherwise PHP script defaults will be used.
if (getenv('LEADERBOARD_TITLE')) {
    define('LEADERBOARD_TITLE', getenv('LEADERBOARD_TITLE'));
}
if (getenv('SEARCH_PLACEHOLDER')) {
    define('SEARCH_PLACEHOLDER', getenv('SEARCH_PLACEHOLDER'));
}
if (getenv('NO_RESULTS_MESSAGE')) {
    define('NO_RESULTS_MESSAGE', getenv('NO_RESULTS_MESSAGE'));
}
if (getenv('POINTS_SUFFIX')) {
    define('POINTS_SUFFIX', getenv('POINTS_SUFFIX'));
}
if (getenv('NO_SCORES_MESSAGE')) {
    define('NO_SCORES_MESSAGE', getenv('NO_SCORES_MESSAGE'));
}

?>
EOF

echo "SUCCESS: ${CONFIG_FILE} generated from environment variables."
echo "Verifying required constants in generated config:"
echo "LIMESURVEY_API_URL: " . (getenv('LIMESURVEY_API_URL') ? 'SET' : 'NOT SET or EMPTY')
echo "LIMESURVEY_USERNAME: " . (getenv('LIMESURVEY_USERNAME') ? 'SET' : 'NOT SET or EMPTY')
# Do not echo password
echo "LIMESURVEY_SURVEY_ID: " . ((int)(getenv('LIMESURVEY_SURVEY_ID') ?: 0) > 0 ? getenv('LIMESURVEY_SURVEY_ID') : 'NOT SET or INVALID')
echo "COLUMN_NICKNAME: " . (getenv('COLUMN_NICKNAME') ?: 'nickname (default from script)') # Updated echo
echo "COLUMN_SCORE: " . (getenv('COLUMN_SCORE') ?: 'totalScore (default from script)')   # Updated echo


# Now, execute the main command passed to this entrypoint script (which is CMD in Dockerfile)
# This will be "apache2-foreground"
exec "$@"
