services:
  - type: web
    name: limesurvey-leaderboard
    env: docker
    plan: free
    buildCommand: ""
    startCommand: php -S 0.0.0.0:10000 -t .
    envVars:
      - key: PORT
        value: 10000
